version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: aieff_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: aiefficiency
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5173:5173"
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://aieff_user:password123@db:5432/aiefficiency
    volumes:
      - .:/app
    command: sh -c "npx drizzle-kit push && npm run dev"

volumes:
  db_data:
